Update template.yaml

diff --git a/template.yaml b/template.yaml
--- a/template.yaml
+++ b/template.yaml
@@ -134,8 +134,14 @@ spec:
             echo "📂 Listing files before running compose:"
             ls -la
             echo "⚙️ Starting docker compose up..."
-            DOCKER_HOST=unix:///var/run/docker.sock docker compose -f docker-compose.yml -f docker-compose.override.yml up --build --force-recreate --remove-orphans 2>&1
+            DOCKER_HOST=unix:///var/run/docker.sock docker compose -f docker-compose.yml -f docker-compose.override.yml up -d --build --force-recreate --remove-orphans
             echo "✅ Docker compose finished with exit code $?"
+            # echo "🐳 Current dir: $(pwd)"
+            # echo "📂 Listing files before running compose:"
+            # ls -la
+            # echo "⚙️ Starting docker compose up..."
+            # DOCKER_HOST=unix:///var/run/docker.sock docker compose -f docker-compose.yml -f docker-compose.override.yml up --build --force-recreate --remove-orphans 2>&1
+            # echo "✅ Docker compose finished with exit code $?"
 
 
         
